name: Ejecutar Bloomberg Scraper

on:
  schedule:
    - cron: "0 15 * * *"  # todos los días a las 15:00 UTC (ajusta si quieres)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Ejecutar script
        run: python main.py
