name: Ejecutar Bloomberg Market Wrap

on:
  schedule:
    - cron: '30 12 * * *'  # Todos los días a las 12:30 UTC
  workflow_dispatch:        # También puedes ejecutarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        EMAIL_TO:   ${{ secrets.EMAIL_TO }}
      run: python main.py
