name: Ejecutar Bloomberg Scraper

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Instalar dependencias de Python y Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Ejecutar script
        run: python main.py
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}

      - name: Ejecutar script
        run: python main.py
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}

      - name: Subir captura de pantalla en caso de error
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-de-error
          path: screenshot_*.png
