name: Bloomberg Scraper Daily

on:
  workflow_dispatch:  # ✅ Permite ejecución manual desde GitHub
  schedule:
    # Ejecutar a las 14:00 UTC (9am hora Perú)
    - cron: '0 14 * * 1-5'
    # Ejecutar a las 21:00 UTC (4pm hora Perú)
    - cron: '0 21 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run scraper script
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: python main.py
